version: '3'
services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: collectorDB
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

    networks:
      strava:
        ipv4_address: 172.18.0.2

  call_and_save:
    image: call_and_save
    build:
      context: .
      dockerfile: Dockerfile.call_and_save
    restart: always
    networks:
      strava:
        ipv4_address: 172.18.0.4

  flask_web:
    image: flask_web
    build:
      context: .
      dockerfile: Dockerfile.flask_web
    restart: always
    ports:
      - "3000:3000"
    networks:
      strava:
        ipv4_address: 172.18.0.3

networks:
  strava:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

volumes:
   mysql:
     external: true
