FROM ubuntu:20.04

WORKDIR /app

COPY requirements.txt .

RUN apt update && apt install python3 -y
RUN apt install python3-pip -y
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 3000

CMD ["python3", "flask_web.py"]
